-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 12:14:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zil3-zpilvenma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zil3-zpilvenma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zil3-zpilvenma` DEFAULT CHARACTER SET utf8 ;
USE `zil3-zpilvenma` ;

-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`POINT_RETRAIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`POINT_RETRAIT` (
  `POINT_RETRAIT_id` INT NOT NULL AUTO_INCREMENT,
  `POINT_RETRAIT_nom` VARCHAR(45) NOT NULL,
  `POINT_RETRAIT_adresse` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`POINT_RETRAIT_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`VENDEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`VENDEUR` (
  `VENDEUR_id` INT NOT NULL AUTO_INCREMENT,
  `VENDEUR_login` VARCHAR(20) NOT NULL,
  `VENDEUR_nom` VARCHAR(60) NOT NULL,
  `VENDEUR_prenom` VARCHAR(60) NOT NULL,
  `VENDEUR_mot_de_passe` VARCHAR(64) NOT NULL,
  `POINT_RETRAIT_id` INT NOT NULL,
  INDEX `fk_VENDEUR_POINT_RETRAIT1_idx` (`POINT_RETRAIT_id` ASC),
  PRIMARY KEY (`VENDEUR_id`),
  UNIQUE INDEX `VENDEUR_login_UNIQUE` (`VENDEUR_login` ASC),
  CONSTRAINT `fk_VENDEUR_POINT_RETRAIT1`
    FOREIGN KEY (`POINT_RETRAIT_id`)
    REFERENCES `zil3-zpilvenma`.`POINT_RETRAIT` (`POINT_RETRAIT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS` (
  `LTQCLAC_id` INT NOT NULL AUTO_INCREMENT,
  `LTQCLAC_login` VARCHAR(20) NOT NULL,
  `LTQCLAC_mot_de_passe` VARCHAR(64) NOT NULL,
  `LTQCLAC_source` TINYINT NOT NULL,
  PRIMARY KEY (`LTQCLAC_id`),
  UNIQUE INDEX `LTQCLAC_login_UNIQUE` (`LTQCLAC_login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`ACTUALITE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`ACTUALITE` (
  `ACTUALITE_id` INT NOT NULL AUTO_INCREMENT,
  `ACTUALITE_titre` VARCHAR(60) NOT NULL,
  `ACTUALITE_description` VARCHAR(300) NULL,
  `ACTUALITE_date` DATE NOT NULL,
  `LTQCLAC_id` INT NOT NULL,
  PRIMARY KEY (`ACTUALITE_id`),
  INDEX `fk_ACTUALITE_LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS1_idx` (`LTQCLAC_id` ASC),
  CONSTRAINT `fk_ACTUALITE_LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS1`
    FOREIGN KEY (`LTQCLAC_id`)
    REFERENCES `zil3-zpilvenma`.`LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS` (`LTQCLAC_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`CATEGORIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`CATEGORIE` (
  `CATEGORIE_id` INT NOT NULL AUTO_INCREMENT,
  `CATEGORIE_nom` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`CATEGORIE_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`ORIGINAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`ORIGINAL` (
  `ORIGINAL_id` INT NOT NULL AUTO_INCREMENT,
  `ORIGINAL_titre` VARCHAR(60) NOT NULL,
  `ORIGINAL_description` VARCHAR(300) NULL,
  `ORIGINAL_nom_image` VARCHAR(100) NULL,
  `LTQCLAC_id` INT NULL,
  `CATEGORIE_id` INT NOT NULL,
  PRIMARY KEY (`ORIGINAL_id`),
  INDEX `fk_ORIGINAL_LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS1_idx` (`LTQCLAC_id` ASC),
  INDEX `fk_ORIGINAL_CATEGORIE1_idx` (`CATEGORIE_id` ASC),
  CONSTRAINT `fk_ORIGINAL_LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS1`
    FOREIGN KEY (`LTQCLAC_id`)
    REFERENCES `zil3-zpilvenma`.`LATABLEQUICONTIENTLESADMINISTRATEURSCOOLS` (`LTQCLAC_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORIGINAL_CATEGORIE1`
    FOREIGN KEY (`CATEGORIE_id`)
    REFERENCES `zil3-zpilvenma`.`CATEGORIE` (`CATEGORIE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`CLIENT` (
  `CLIENT_id` INT NOT NULL AUTO_INCREMENT,
  `CLIENT_code` CHAR(8) NOT NULL,
  `CLIENT_nom` VARCHAR(60) NOT NULL,
  `CLIENT_prenom` VARCHAR(60) NOT NULL,
  `CLIENT_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`CLIENT_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`COMMANDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`COMMANDE` (
  `COMMANDE_id` INT NOT NULL AUTO_INCREMENT,
  `COMMANDE_etat` CHAR(1) NOT NULL,
  `COMMANDE_date` DATE NOT NULL,
  `COMMANDE_date_retrait` DATE NULL,
  `COMMANDE_code` CHAR(20) NOT NULL,
  `POINT_RETRAIT_id` INT NOT NULL,
  `CLIENT_id` INT NOT NULL,
  PRIMARY KEY (`COMMANDE_id`),
  INDEX `fk_COMMANDE_POINT_RETRAIT1_idx` (`POINT_RETRAIT_id` ASC),
  INDEX `fk_COMMANDE_CLIENT1_idx` (`CLIENT_id` ASC),
  CONSTRAINT `fk_COMMANDE_POINT_RETRAIT1`
    FOREIGN KEY (`POINT_RETRAIT_id`)
    REFERENCES `zil3-zpilvenma`.`POINT_RETRAIT` (`POINT_RETRAIT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMANDE_CLIENT1`
    FOREIGN KEY (`CLIENT_id`)
    REFERENCES `zil3-zpilvenma`.`CLIENT` (`CLIENT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`GOODIE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`GOODIE_TYPE` (
  `GOODIE_TYPE_id` INT NOT NULL AUTO_INCREMENT,
  `GOODIE_TYPE_nom` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`GOODIE_TYPE_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`GOODIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`GOODIE` (
  `GOODIE_id` INT NOT NULL AUTO_INCREMENT,
  `GOODIE_nom` VARCHAR(100) NOT NULL,
  `GOODIE_nb_en_stock` INT NOT NULL,
  `GOODIE_description` VARCHAR(300) NULL,
  `GOODIE_nom_image` VARCHAR(100) NULL,
  `GOODIE_prix` DOUBLE NOT NULL,
  `GOODIE_TYPE_id` INT NOT NULL,
  PRIMARY KEY (`GOODIE_id`),
  INDEX `fk_GOODIE_type_GOODIE1_idx` (`GOODIE_TYPE_id` ASC),
  CONSTRAINT `fk_GOODIE_type_GOODIE1`
    FOREIGN KEY (`GOODIE_TYPE_id`)
    REFERENCES `zil3-zpilvenma`.`GOODIE_TYPE` (`GOODIE_TYPE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`ACTUALITE_SE_REFERE_A_ORIGINAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`ACTUALITE_SE_REFERE_A_ORIGINAL` (
  `ACTUALITE_id` INT NOT NULL,
  `ORIGINAL_id` INT NOT NULL,
  PRIMARY KEY (`ACTUALITE_id`, `ORIGINAL_id`),
  INDEX `fk_ACTUALITE_has_ORIGINAL_ORIGINAL1_idx` (`ORIGINAL_id` ASC),
  INDEX `fk_ACTUALITE_has_ORIGINAL_ACTUALITE1_idx` (`ACTUALITE_id` ASC),
  CONSTRAINT `fk_ACTUALITE_has_ORIGINAL_ACTUALITE1`
    FOREIGN KEY (`ACTUALITE_id`)
    REFERENCES `zil3-zpilvenma`.`ACTUALITE` (`ACTUALITE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACTUALITE_has_ORIGINAL_ORIGINAL1`
    FOREIGN KEY (`ORIGINAL_id`)
    REFERENCES `zil3-zpilvenma`.`ORIGINAL` (`ORIGINAL_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`ORIGINAL_CONTIENT_GOODIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`ORIGINAL_CONTIENT_GOODIES` (
  `ORIGINAL_id` INT NOT NULL,
  `GOODIE_id` INT NOT NULL,
  PRIMARY KEY (`ORIGINAL_id`, `GOODIE_id`),
  INDEX `fk_ORIGINAL_has_GOODIE_GOODIE1_idx` (`GOODIE_id` ASC),
  INDEX `fk_ORIGINAL_has_GOODIE_ORIGINAL1_idx` (`ORIGINAL_id` ASC),
  CONSTRAINT `fk_ORIGINAL_has_GOODIE_ORIGINAL1`
    FOREIGN KEY (`ORIGINAL_id`)
    REFERENCES `zil3-zpilvenma`.`ORIGINAL` (`ORIGINAL_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORIGINAL_has_GOODIE_GOODIE1`
    FOREIGN KEY (`GOODIE_id`)
    REFERENCES `zil3-zpilvenma`.`GOODIE` (`GOODIE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zpilvenma`.`COMMANDE_CONTIENT_GOODIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zil3-zpilvenma`.`COMMANDE_CONTIENT_GOODIES` (
  `COMMANDE_id` INT NOT NULL,
  `GOODIE_id` INT NOT NULL,
  `CCG_quantite` INT NOT NULL,
  PRIMARY KEY (`COMMANDE_id`, `GOODIE_id`),
  INDEX `fk_COMMANDE_has_GOODIE_GOODIE1_idx` (`GOODIE_id` ASC),
  INDEX `fk_COMMANDE_has_GOODIE_COMMANDE1_idx` (`COMMANDE_id` ASC),
  CONSTRAINT `fk_COMMANDE_has_GOODIE_COMMANDE1`
    FOREIGN KEY (`COMMANDE_id`)
    REFERENCES `zil3-zpilvenma`.`COMMANDE` (`COMMANDE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMANDE_has_GOODIE_GOODIE1`
    FOREIGN KEY (`GOODIE_id`)
    REFERENCES `zil3-zpilvenma`.`GOODIE` (`GOODIE_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
